### PR TITLE
Fix dont call prototypes warning

### PR DESCRIPTION
**Pull request by gruberro**
By passing `...rest` deprecation warnings are supressed.
Details can be found [in the official documentation](https://facebook.github.io/react/warnings/dont-call-proptypes.html)

### CODE REVIEW

**Comment by gruberro** [comment]
ping @evcohen I've no idea why installing the npm requirements is failing... maybe you can give me a hint?

**Comment by yantakus** [comment]
Any update on this?

**Comment by beefancohen** [comment]
@gruberro @web2style taking a look now, sorry!

**Comment by beefancohen** [comment]
Fixed in [v1.0.3](https://github.com/evcohen/react-proptype-conditional-require/releases/tag/1.0.3)

**Comment by gruberro** [comment]
Thank you @evcohen!

**Pull request merged**
